name: CI Workflow

on:
  push:
    branches:
      - main

jobs:
  security_check:
    name: Security Check with Bandit
    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12.2'

      - name: Install Bandit
        run: |
          pip install bandit  # Устанавливаем Bandit для проверки безопасности

      - name: Run security check
        run: |
         bandit -r . -x ./venv -x ./.git --exclude ./venv/Lib/site-packages --skip B101,B110,B602,B603,B605,B607

  openapi_generation:
    name: Generate OpenAPI Documentation
    runs-on: ubuntu-latest
    needs: security_check

    steps:
      - name: Checkout the code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12.2'

      - name: Install Dependencies
        run: |
          pip install flask flasgger  # Устанавливаем Flask и Flasgger для работы с OpenAPI

      - name: Run Flask application in background
        run: |
          flask run --host=0.0.0.0 --port=5000 --debug &  # Запускаем сервер в фоне с флагом debug

      - name: Wait for Flask to start
        run: sleep 10

      - name: Generate OpenAPI Specification (openapi.yaml)
        run: |
          curl http://localhost:5000/swagger.json -o openapi.yaml  # Получаем OpenAPI спецификацию

      - name: Check if openapi.yaml exists
        run: |
          ls -la openapi.yaml  # Проверяем, существует ли файл openapi.yaml

      - name: Upload OpenAPI Spec as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: openapi-spec
          path: openapi.yaml

  redoc_generation:
    name: Generate ReDoc Page
    runs-on: ubuntu-latest
    needs: openapi_generation

    steps:
      - name: Check out the code
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install redocly
        run: |
          npm install -g @redocly/cli@latest  

      - name: Check if openapi.yaml exists
        run: |
          ls -la openapi.yaml

      - name: Generate ReDoc HTML
        run: |
          redocly build-docs openapi.yaml --output docs/index.html

  deploy_to_pages:
    name: Deploy Documentation to GitHub Pages
    runs-on: ubuntu-latest
    needs: redoc_generation 

    steps:
      - name: Check out the code
        uses: actions/checkout@v4

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs